# Generated by Django 5.2.5 on 2025-09-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_nome_usuario_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('Fazer', 'Fazer'), ('Fazendo', 'Fazendo'), ('Feito', 'Feito')], default='Fazer', max_length=10),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='descricao',
            field=models.TextField(max_length=255),
        ),
    ]
